### ISSUE TITLE
questions about  the uploaded indoor map

### ISSUE THREAD

**Issue by eden57** [eegeo/eegeo-indoor-maps-api#1]
eegeo api is really amazing. Thanks to the team!

I am trying to upload indoor map data to eegeo and wish to know rules about accessing the uploaded data via eegeo sdk.  

Is there any authorization related with developer token or app key ? Or else everyone use this sdk will be able to view the map that has been uploaded ?

really appreciate for your response :)

**Comment by johnbell84** [comment]
Hi eden57,

Thanks for trying the indoor maps API!

If you submit an indoor map via the API you will be returned the URL of a manifest.  This is a configuration file which tells the SDK where to get its data from (including the data for your indoor map).  Anyone who has a build which is configured to look at your indoor map's manifest will be able to view your indoor map, but it's up to you whether or how you distribute the manifest link.

We do have some users who require stronger privacy for their indoor map data, and have been able to create solutions for them.  If that's something you'd like to talk about, please let us know.

Best regards,

John

**Comment by eden57** [comment]
John，

Thanks very much！  

My status has been {"status":"AwaitingApproval"} for 3 days.
Is that normal ?  And how long this operation generally requires ?  

Best regards,

Eden

**Comment by johnbell84** [comment]
Hi Eden,

We’ve approved the submission, so you should be able to upload your indoor map now.  Sorry for the delay on this.

It might be worth noting that I’m afraid we don’t have any exterior map data for China yet.  You should still be able to submit your indoor map and view it in the world, but the surrounding region won’t be present.  

Hopefully the indoor map will be enough to get you started, but we’ll certainly take your interest in getting exterior coverage of China into account when prioritising future map updates.

Best regards,

John

**Comment by johnbell84** [comment]
Closing this issue as assuming resolved.
