### ISSUE TITLE
Can we use indoor maps offline?

### ISSUE THREAD

**Issue by am2222** [eegeo/eegeo-indoor-maps-api#2]
Hi,
Can we use indoor maps offline?I mean we feed SDK with geojson and dont host our maps on eegeo servers?
Is it possible?
thanks

**Comment by tim-jenks** [comment]
Hello,

You are able to use our indoor maps offline using the [offline capabilities of the eeGeo SDK](http://www.eegeo.com/features/offline/). The data is hosted on our CDN and cached or precached on your device via the SDK.

We do support on-premises hosting of our maps via enterprise licensing, please contact enquiries@eegeo.com for more information.

-Tim

**Comment by am2222** [comment]
Thanks for your answer, But Here I am cnfused, To create an indoor map it seems that we are forced to upload our maps into your CDN,Right??I mean Can we use your sdk for free and host our map data on our hosts?

**Comment by tim-jenks** [comment]
Thanks for the question, I hope this clarifies!

* You can upload your indoor maps in our [GeoJSON Indoor Maps](https://github.com/eegeo/eegeo-indoor-maps-api/blob/master/FORMAT.md) format to our [indoor maps API](https://github.com/eegeo/eegeo-indoor-maps-api/)
* The indoor maps API builds 3D indoor maps and hosts on our CDN. 
* You can then use  [eegeo.js](https://github.com/eegeo/eegeo.js), or our [iOS API](https://github.com/eegeo/ios-api) or [C++ APIs](https://github.com/eegeo/eegeo-example-app) to deliver these indoor maps to your devices.
* Our APIs provide offline access via caching [and precaching](https://github.com/eegeo/eegeo-sdk-samples/blob/master/src/Examples/SingleCity/SingleCityExample.cpp#L111)
* The is covered in our standard pricing

Hosting on premises or on your own CDN is not covered via our standard pricing, if you wish to host data yourself, you would need enterprise pricing - please contact enquiries@eegeo.com for details of our enterprise pricing.
